version: '3'
services:
    php-fpm:
        image: cyberduck/php-fpm-laravel:8.2
        environment:
            XDEBUG: false
            # REMOTE_HOST: "<HOSTIP>" # If not set the default is 'host.docker.internal' which will work on OSX and windows
        volumes:
            - ./www:/var/www/
            - ~/.ssh:/root/.ssh # can be useful for composer if you use private CVS
    caddy:
      image: caddy:2.7.2-alpine
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
      volumes:
        - ./caddy/Caddyfile:/etc/caddy/Caddyfile
        - ./www:/var/www
        - caddy_data:/data
        - caddy_config:/config